/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Atspm Configuration Api
 * Atspm Device and Location Configuration
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  DetectorComment
} from '../config-api.schemas';

import {
  getGetDetectorCommentCountResponseMock,
  getGetDetectorCommentFromKeyResponseMock,
  getGetDetectorCommentResponseMock
} from './detector-comment.faker';

export { getGetDetectorCommentResponseMock, getGetDetectorCommentCountResponseMock, getGetDetectorCommentFromKeyResponseMock } from './detector-comment.faker';


export const getGetDetectorCommentMockHandler = (overrideResponse?: DetectorComment[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DetectorComment[]> | DetectorComment[]), options?: RequestHandlerOptions) => {
  return http.get('*/DetectorComment', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDetectorCommentResponseMock(),
      { status: 200, headers: { 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true' }
      })
  }, options)
}

export const getPostDetectorCommentMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/DetectorComment', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 201
      })
  }, options)
}

export const getGetDetectorCommentCountMockHandler = (overrideResponse?: DetectorComment[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DetectorComment[]> | DetectorComment[]), options?: RequestHandlerOptions) => {
  return http.get('*/DetectorComment/$count', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDetectorCommentCountResponseMock(),
      { status: 200, headers: { 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true' }
      })
  }, options)
}

export const getGetDetectorCommentFromKeyMockHandler = (overrideResponse?: DetectorComment | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DetectorComment> | DetectorComment), options?: RequestHandlerOptions) => {
  return http.get('*/DetectorComment/:key', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetDetectorCommentFromKeyResponseMock(),
      { status: 200, headers: { 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true' }
      })
  }, options)
}

export const getPutDetectorCommentFromKeyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/DetectorComment/:key', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getPatchDetectorCommentFromKeyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.patch('*/DetectorComment/:key', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getDeleteDetectorCommentFromKeyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/DetectorComment/:key', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}
export const getDetectorCommentMock = () => [
  getGetDetectorCommentMockHandler(),
  getPostDetectorCommentMockHandler(),
  getGetDetectorCommentCountMockHandler(),
  getGetDetectorCommentFromKeyMockHandler(),
  getPutDetectorCommentFromKeyMockHandler(),
  getPatchDetectorCommentFromKeyMockHandler(),
  getDeleteDetectorCommentFromKeyMockHandler()
]
