/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Atspm Configuration Api
 * Atspm Device and Location Configuration
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Product
} from '../config-api.schemas';

import {
  getGetProductCountResponseMock,
  getGetProductFromKeyResponseMock,
  getGetProductResponseMock
} from './product.faker';

export { getGetProductResponseMock, getGetProductCountResponseMock, getGetProductFromKeyResponseMock } from './product.faker';


export const getGetProductMockHandler = (overrideResponse?: Product[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Product[]> | Product[]), options?: RequestHandlerOptions) => {
  return http.get('*/Product', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProductResponseMock(),
      { status: 200, headers: { 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true' }
      })
  }, options)
}

export const getPostProductMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/Product', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 201
      })
  }, options)
}

export const getGetProductCountMockHandler = (overrideResponse?: Product[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Product[]> | Product[]), options?: RequestHandlerOptions) => {
  return http.get('*/Product/$count', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProductCountResponseMock(),
      { status: 200, headers: { 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true' }
      })
  }, options)
}

export const getGetProductFromKeyMockHandler = (overrideResponse?: Product | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Product> | Product), options?: RequestHandlerOptions) => {
  return http.get('*/Product/:key', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProductFromKeyResponseMock(),
      { status: 200, headers: { 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true' }
      })
  }, options)
}

export const getPutProductFromKeyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/Product/:key', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getPatchProductFromKeyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.patch('*/Product/:key', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getDeleteProductFromKeyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/Product/:key', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}
export const getProductMock = () => [
  getGetProductMockHandler(),
  getPostProductMockHandler(),
  getGetProductCountMockHandler(),
  getGetProductFromKeyMockHandler(),
  getPutProductFromKeyMockHandler(),
  getPatchProductFromKeyMockHandler(),
  getDeleteProductFromKeyMockHandler()
]
