/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * ATSPM Log Data Api
 * ATSPM Log Data with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';


export const getGetEventLogDataTypesResponseMock = (): string[] => (Array.from({length: faker.number.int({min: 1,max: 10})}, () => faker.word.sample()))


export const getGetEventLogDataTypesMockHandler = (overrideResponse?: string[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<string[]> | string[])) => {
  return http.get('*/api/v1/EventLog/GetDataTypes', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetEventLogDataTypesResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetEventLogArchivedEventsFromLocationIdentifierMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void)) => {
  return http.get('*/api/v1/EventLog/GetArchivedEvents/:locationIdentifier', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}

export const getGetEventLogArchivedEventsFromLocationIdentifierAndDeviceIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void)) => {
  return http.get('*/api/v1/EventLog/GetArchivedEvents/:locationIdentifier/:deviceId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}

export const getGetEventLogArchivedEventsFromLocationIdentifierAndDataTypeMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void)) => {
  return http.get('*/api/v1/EventLog/GetArchivedEvents/:locationIdentifier/:dataType', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}

export const getGetEventLogArchivedEventsFromLocationIdentifierAndDeviceIdAndDataTypeMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void)) => {
  return http.get('*/api/v1/EventLog/GetArchivedEvents/:locationIdentifier/:deviceId/:dataType', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}

export const getGetEventLogDaysWithEventLogsFromLocationIdentifierMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void)) => {
  return http.get('*/api/v1/EventLog/GetDaysWithEventLogs/:locationIdentifier', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}
export const getEventLogMock = () => [
  getGetEventLogDataTypesMockHandler(),
  getGetEventLogArchivedEventsFromLocationIdentifierMockHandler(),
  getGetEventLogArchivedEventsFromLocationIdentifierAndDeviceIdMockHandler(),
  getGetEventLogArchivedEventsFromLocationIdentifierAndDataTypeMockHandler(),
  getGetEventLogArchivedEventsFromLocationIdentifierAndDeviceIdAndDataTypeMockHandler(),
  getGetEventLogDaysWithEventLogsFromLocationIdentifierMockHandler()
]
