/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ATSPM Speed Management Api
 * ATSPM Log Data with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  getGetApiV1AccessCategoryResponseMock,
  getGetApiV1CityResponseMock,
  getGetApiV1CountyResponseMock,
  getGetApiV1FunctionalTypeResponseMock,
  getGetApiV1ImpactResponseMock,
  getGetApiV1ImpactTypeIdResponseMock,
  getGetApiV1ImpactTypeResponseMock,
  getGetApiV1MonthlyAggregationLatestMonthAggClassificationTimePeriodResponseMock,
  getGetApiV1MonthlyAggregationSegmentsSegmentIdMonthAggClassificationTimePeriodResponseMock,
  getGetApiV1RegionResponseMock,
  getGetImpactByIdResponseMock,
  getPostApiV1CongestionTrackingGetReportDataResponseMock,
  getPostApiV1DataQualityGetReportDataResponseMock,
  getPostApiV1EffectivenessOfStrategiesGetReportDataResponseMock,
  getPostApiV1ExportableReportsGetReportDataResponseMock,
  getPostApiV1ImpactHotspotsResponseMock,
  getPostApiV1ImpactResponseMock,
  getPostApiV1ImpactTypeResponseMock,
  getPostApiV1MonthlyAggregationHotspotsResponseMock,
  getPostApiV1SegmentSegmentIdSpeedsResponseMock,
  getPostApiV1SegmentSpeedsResponseMock,
  getPostApiV1SpeedComplianceGetReportDataResponseMock,
  getPostApiV1SpeedFromImpactImpactImpactIdResponseMock,
  getPostApiV1SpeedFromImpactSegmentSegmentIdResponseMock,
  getPostApiV1SpeedManagementGetDailyHistoricalSpeedsResponseMock,
  getPostApiV1SpeedManagementGetMonthlyHistoricalSpeedsResponseMock,
  getPostApiV1SpeedOverDistanceGetReportDataResponseMock,
  getPostApiV1SpeedOverTimeGetReportDataResponseMock,
  getPostApiV1SpeedVariabilityGetReportDataResponseMock,
  getPostApiV1SpeedViolationsGetReportDataResponseMock,
  getPostApiV1ViolationsAndExtremeViolationsGetReportDataResponseMock,
  getPutApiV1ImpactIdImpactTypeImpactTypeIdResponseMock,
  getPutApiV1ImpactIdResponseMock,
  getPutApiV1ImpactIdSegmentsSegmentIdResponseMock,
  getPutApiV1ImpactTypeIdResponseMock
} from './aTSPMSpeedManagementApi.faker';

import type {
  CongestionTrackingDto,
  DailyHistoricalRouteData,
  DataQualitySource,
  EffectivenessOfStrategiesDto,
  ExportableReportResult,
  HourlySpeed,
  Impact,
  ImpactDto,
  ImpactType,
  MonthlyAggregationSimplified,
  MonthlyHistoricalRouteData,
  NameAndIdDto,
  RouteSpeed,
  SpeedComplianceDto,
  SpeedFromImpactDto,
  SpeedOverDistanceDto,
  SpeedOverTimeDto,
  SpeedVariabilityDto,
  SpeedViolationsDto,
  ViolationsAndExtremeViolationsDto
} from './aTSPMSpeedManagementApi.schemas';

export { getGetApiV1AccessCategoryResponseMock, getGetApiV1CityResponseMock, getPostApiV1CongestionTrackingGetReportDataResponseMock, getGetApiV1CountyResponseMock, getPostApiV1DataQualityGetReportDataResponseMock, getPostApiV1EffectivenessOfStrategiesGetReportDataResponseMock, getPostApiV1ExportableReportsGetReportDataResponseMock, getGetApiV1FunctionalTypeResponseMock, getGetApiV1ImpactResponseMock, getPostApiV1ImpactResponseMock, getGetImpactByIdResponseMock, getPutApiV1ImpactIdResponseMock, getPutApiV1ImpactIdSegmentsSegmentIdResponseMock, getPutApiV1ImpactIdImpactTypeImpactTypeIdResponseMock, getPostApiV1ImpactHotspotsResponseMock, getGetApiV1ImpactTypeResponseMock, getPostApiV1ImpactTypeResponseMock, getGetApiV1ImpactTypeIdResponseMock, getPutApiV1ImpactTypeIdResponseMock, getGetApiV1MonthlyAggregationLatestMonthAggClassificationTimePeriodResponseMock, getPostApiV1MonthlyAggregationHotspotsResponseMock, getGetApiV1MonthlyAggregationSegmentsSegmentIdMonthAggClassificationTimePeriodResponseMock, getGetApiV1RegionResponseMock, getPostApiV1SegmentSpeedsResponseMock, getPostApiV1SegmentSegmentIdSpeedsResponseMock, getPostApiV1SpeedComplianceGetReportDataResponseMock, getPostApiV1SpeedFromImpactImpactImpactIdResponseMock, getPostApiV1SpeedFromImpactSegmentSegmentIdResponseMock, getPostApiV1SpeedManagementGetMonthlyHistoricalSpeedsResponseMock, getPostApiV1SpeedManagementGetDailyHistoricalSpeedsResponseMock, getPostApiV1SpeedOverDistanceGetReportDataResponseMock, getPostApiV1SpeedOverTimeGetReportDataResponseMock, getPostApiV1SpeedVariabilityGetReportDataResponseMock, getPostApiV1SpeedViolationsGetReportDataResponseMock, getPostApiV1ViolationsAndExtremeViolationsGetReportDataResponseMock } from './aTSPMSpeedManagementApi.faker';


export const getGetApiV1AccessCategoryMockHandler = (overrideResponse?: NameAndIdDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<NameAndIdDto[]> | NameAndIdDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/AccessCategory', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiV1AccessCategoryResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetApiV1CityMockHandler = (overrideResponse?: NameAndIdDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<NameAndIdDto[]> | NameAndIdDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/City', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiV1CityResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1CongestionTrackingGetReportDataMockHandler = (overrideResponse?: CongestionTrackingDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CongestionTrackingDto> | CongestionTrackingDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/CongestionTracking/getReportData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1CongestionTrackingGetReportDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetApiV1CountyMockHandler = (overrideResponse?: NameAndIdDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<NameAndIdDto[]> | NameAndIdDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/County', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiV1CountyResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1DataImporterStartRedownloadMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<unknown> | unknown), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/DataImporter/StartRedownload', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1DataImporterDownloadHourlyDataMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<unknown> | unknown), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/DataImporter/DownloadHourlyData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1DataImporterDownloadClearguideHourlyMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<unknown> | unknown), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/DataImporter/DownloadClearguideHourly', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1DataImporterClearTempDataForClearguideMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<unknown> | unknown), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/DataImporter/ClearTempDataForClearguide', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1DataQualityGetReportDataMockHandler = (overrideResponse?: DataQualitySource[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DataQualitySource[]> | DataQualitySource[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/DataQuality/getReportData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1DataQualityGetReportDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1EffectivenessOfStrategiesGetReportDataMockHandler = (overrideResponse?: EffectivenessOfStrategiesDto[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<EffectivenessOfStrategiesDto[]> | EffectivenessOfStrategiesDto[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/EffectivenessOfStrategies/getReportData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1EffectivenessOfStrategiesGetReportDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1EntityGetEntitiesWithinRangeMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/Entity/GetEntitiesWithinRange', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1EntityFileGeojsonFetchFileMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/EntityFile/geojson/fetch-file', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1EntityFileShapefileFetchFileMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/EntityFile/shapefile/fetch-file', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1EntityFileAtspmRefreshMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/EntityFile/atspm/refresh', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1EntityVersionTablesMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/EntityVersion/tables', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getDeleteApiV1EntityVersionCopiesMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/EntityVersion/copies', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1EntityVersionEntitiesTableIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/EntityVersion/entities/:tableId', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1EntityVersionEntitiesTableIdAreaMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/EntityVersion/entities/:tableId/area', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1EntityVersionEntitiesAreaMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/EntityVersion/entities/area', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1ExportableReportsGetReportDataMockHandler = (overrideResponse?: ExportableReportResult[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ExportableReportResult[]> | ExportableReportResult[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/ExportableReports/getReportData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1ExportableReportsGetReportDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetApiV1FunctionalTypeMockHandler = (overrideResponse?: NameAndIdDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<NameAndIdDto[]> | NameAndIdDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/FunctionalType', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiV1FunctionalTypeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetApiV1ImpactMockHandler = (overrideResponse?: Impact[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Impact[]> | Impact[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/Impact', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiV1ImpactResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1ImpactMockHandler = (overrideResponse?: Impact | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Impact> | Impact), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/Impact', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1ImpactResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetImpactByIdMockHandler = (overrideResponse?: Impact | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Impact> | Impact), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/Impact/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetImpactByIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPutApiV1ImpactIdMockHandler = (overrideResponse?: Impact | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<Impact> | Impact), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/Impact/:id', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPutApiV1ImpactIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteApiV1ImpactIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/Impact/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getPutApiV1ImpactIdSegmentsSegmentIdMockHandler = (overrideResponse?: Impact | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<Impact> | Impact), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/Impact/:id/segments/:segmentId', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPutApiV1ImpactIdSegmentsSegmentIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteApiV1ImpactIdSegmentsSegmentIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/Impact/:id/segments/:segmentId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getPutApiV1ImpactIdImpactTypeImpactTypeIdMockHandler = (overrideResponse?: Impact | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<Impact> | Impact), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/Impact/:id/impactType/:impactTypeId', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPutApiV1ImpactIdImpactTypeImpactTypeIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteApiV1ImpactIdImpactTypeImpactTypeIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/Impact/:id/impactType/:impactTypeId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getPostApiV1ImpactHotspotsMockHandler = (overrideResponse?: ImpactDto[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ImpactDto[]> | ImpactDto[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/Impact/hotspots', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1ImpactHotspotsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1ImpactAggregateIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/Impact/aggregate/:id', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1ImpactAggregateMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/Impact/aggregate', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1ImpactTypeMockHandler = (overrideResponse?: ImpactType[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ImpactType[]> | ImpactType[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/ImpactType', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiV1ImpactTypeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1ImpactTypeMockHandler = (overrideResponse?: ImpactType | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ImpactType> | ImpactType), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/ImpactType', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1ImpactTypeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetApiV1ImpactTypeIdMockHandler = (overrideResponse?: ImpactType | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ImpactType> | ImpactType), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/ImpactType/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiV1ImpactTypeIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPutApiV1ImpactTypeIdMockHandler = (overrideResponse?: ImpactType | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<ImpactType> | ImpactType), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/ImpactType/:id', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPutApiV1ImpactTypeIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteApiV1ImpactTypeIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/ImpactType/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getPostApiV1MonthlyAggregationMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<unknown> | unknown), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/MonthlyAggregation', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getDeleteApiV1MonthlyAggregationMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/MonthlyAggregation', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1MonthlyAggregationLatestMonthAggClassificationTimePeriodMockHandler = (overrideResponse?: MonthlyAggregationSimplified[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MonthlyAggregationSimplified[]> | MonthlyAggregationSimplified[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/MonthlyAggregation/latest/:monthAggClassification/:timePeriod', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiV1MonthlyAggregationLatestMonthAggClassificationTimePeriodResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1MonthlyAggregationHotspotsMockHandler = (overrideResponse?: RouteSpeed[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<RouteSpeed[]> | RouteSpeed[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/MonthlyAggregation/hotspots', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1MonthlyAggregationHotspotsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1MonthlyAggregationSourceSourceIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/MonthlyAggregation/source/:sourceId', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1MonthlyAggregationSegmentMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/MonthlyAggregation/segment', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getDeleteApiV1MonthlyAggregationDuplicatesMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/MonthlyAggregation/duplicates', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1MonthlyAggregationSegmentsSegmentIdMonthAggClassificationTimePeriodMockHandler = (overrideResponse?: MonthlyAggregationSimplified[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MonthlyAggregationSimplified[]> | MonthlyAggregationSimplified[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/MonthlyAggregation/segments/:segmentId/:monthAggClassification/:timePeriod', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiV1MonthlyAggregationSegmentsSegmentIdMonthAggClassificationTimePeriodResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetApiV1MonthlyAggregationFilteringTimePeriodsMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/MonthlyAggregation/filtering-time-periods', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1MonthlyAggregationMonthAggClassificationsMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/MonthlyAggregation/month-agg-classifications', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1MonthlyAggregationSpeedCategoryFiltersMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/MonthlyAggregation/speed-category-filters', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1RegionMockHandler = (overrideResponse?: NameAndIdDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<NameAndIdDto[]> | NameAndIdDto[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/Region', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiV1RegionResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetApiV1SegmentMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/Segment', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1SegmentMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/Segment', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1SegmentAllSegmentsMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/Segment/AllSegments', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetApiV1SegmentSegmentIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/Segment/:segmentId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1SegmentSpeedsMockHandler = (overrideResponse?: HourlySpeed[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<HourlySpeed[]> | HourlySpeed[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/Segment/speeds', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1SegmentSpeedsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1SegmentSegmentIdSpeedsMockHandler = (overrideResponse?: HourlySpeed[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<HourlySpeed[]> | HourlySpeed[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/Segment/:segmentId/speeds', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1SegmentSegmentIdSpeedsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1SegmentAddSegmentMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/Segment/AddSegment', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 201
      })
  }, options)
}

export const getPostApiV1SegmentSegmentIdEntitiesReplaceMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/Segment/:segmentId/Entities/Replace', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 201
      })
  }, options)
}

export const getPostApiV1SegmentSegmentIdEntitiesAddMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/Segment/:segmentId/Entities/Add', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 201
      })
  }, options)
}

export const getDeleteApiV1SegmentSegmentIdEntitiesDeleteMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/Segment/:segmentId/Entities/Delete', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 201
      })
  }, options)
}

export const getPutApiV1SegmentUpdateSegmentSegmentIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/api/v1/Segment/UpdateSegment/:segmentId', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getDeleteApiV1SegmentDeleteSegmentSegmentIdMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<unknown> | unknown), options?: RequestHandlerOptions) => {
  return http.delete('*/api/v1/Segment/DeleteSegment/:segmentId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1SpeedComplianceGetReportDataMockHandler = (overrideResponse?: SpeedComplianceDto[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SpeedComplianceDto[]> | SpeedComplianceDto[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/SpeedCompliance/getReportData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1SpeedComplianceGetReportDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1SpeedFromImpactImpactImpactIdMockHandler = (overrideResponse?: SpeedFromImpactDto[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SpeedFromImpactDto[]> | SpeedFromImpactDto[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/SpeedFromImpact/impact/:impactId', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1SpeedFromImpactImpactImpactIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1SpeedFromImpactSegmentSegmentIdMockHandler = (overrideResponse?: SpeedFromImpactDto[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SpeedFromImpactDto[]> | SpeedFromImpactDto[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/SpeedFromImpact/segment/:segmentId', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1SpeedFromImpactSegmentSegmentIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetRouteSpeedsMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/SpeedManagement/GetRouteSpeeds', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiV1SpeedManagementGetMonthlyHistoricalSpeedsMockHandler = (overrideResponse?: MonthlyHistoricalRouteData[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<MonthlyHistoricalRouteData[]> | MonthlyHistoricalRouteData[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/SpeedManagement/GetMonthlyHistoricalSpeeds', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1SpeedManagementGetMonthlyHistoricalSpeedsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1SpeedManagementGetDailyHistoricalSpeedsMockHandler = (overrideResponse?: DailyHistoricalRouteData[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DailyHistoricalRouteData[]> | DailyHistoricalRouteData[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/SpeedManagement/GetDailyHistoricalSpeeds', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1SpeedManagementGetDailyHistoricalSpeedsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1SpeedOverDistanceGetReportDataMockHandler = (overrideResponse?: SpeedOverDistanceDto[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SpeedOverDistanceDto[]> | SpeedOverDistanceDto[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/SpeedOverDistance/getReportData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1SpeedOverDistanceGetReportDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1SpeedOverTimeGetReportDataMockHandler = (overrideResponse?: SpeedOverTimeDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SpeedOverTimeDto> | SpeedOverTimeDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/SpeedOverTime/getReportData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1SpeedOverTimeGetReportDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1SpeedVariabilityGetReportDataMockHandler = (overrideResponse?: SpeedVariabilityDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SpeedVariabilityDto> | SpeedVariabilityDto), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/SpeedVariability/getReportData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1SpeedVariabilityGetReportDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1SpeedViolationsGetReportDataMockHandler = (overrideResponse?: SpeedViolationsDto[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SpeedViolationsDto[]> | SpeedViolationsDto[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/SpeedViolations/getReportData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1SpeedViolationsGetReportDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiV1ViolationsAndExtremeViolationsGetReportDataMockHandler = (overrideResponse?: ViolationsAndExtremeViolationsDto[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ViolationsAndExtremeViolationsDto[]> | ViolationsAndExtremeViolationsDto[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/ViolationsAndExtremeViolations/getReportData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiV1ViolationsAndExtremeViolationsGetReportDataResponseMock(),
      { status: 200
      })
  }, options)
}
export const getATSPMSpeedManagementApiMock = () => [
  getGetApiV1AccessCategoryMockHandler(),
  getGetApiV1CityMockHandler(),
  getPostApiV1CongestionTrackingGetReportDataMockHandler(),
  getGetApiV1CountyMockHandler(),
  getPostApiV1DataImporterStartRedownloadMockHandler(),
  getPostApiV1DataImporterDownloadHourlyDataMockHandler(),
  getPostApiV1DataImporterDownloadClearguideHourlyMockHandler(),
  getPostApiV1DataImporterClearTempDataForClearguideMockHandler(),
  getPostApiV1DataQualityGetReportDataMockHandler(),
  getPostApiV1EffectivenessOfStrategiesGetReportDataMockHandler(),
  getPostApiV1EntityGetEntitiesWithinRangeMockHandler(),
  getPostApiV1EntityFileGeojsonFetchFileMockHandler(),
  getPostApiV1EntityFileShapefileFetchFileMockHandler(),
  getPostApiV1EntityFileAtspmRefreshMockHandler(),
  getPostApiV1EntityVersionTablesMockHandler(),
  getDeleteApiV1EntityVersionCopiesMockHandler(),
  getPostApiV1EntityVersionEntitiesTableIdMockHandler(),
  getPostApiV1EntityVersionEntitiesTableIdAreaMockHandler(),
  getPostApiV1EntityVersionEntitiesAreaMockHandler(),
  getPostApiV1ExportableReportsGetReportDataMockHandler(),
  getGetApiV1FunctionalTypeMockHandler(),
  getGetApiV1ImpactMockHandler(),
  getPostApiV1ImpactMockHandler(),
  getGetImpactByIdMockHandler(),
  getPutApiV1ImpactIdMockHandler(),
  getDeleteApiV1ImpactIdMockHandler(),
  getPutApiV1ImpactIdSegmentsSegmentIdMockHandler(),
  getDeleteApiV1ImpactIdSegmentsSegmentIdMockHandler(),
  getPutApiV1ImpactIdImpactTypeImpactTypeIdMockHandler(),
  getDeleteApiV1ImpactIdImpactTypeImpactTypeIdMockHandler(),
  getPostApiV1ImpactHotspotsMockHandler(),
  getPostApiV1ImpactAggregateIdMockHandler(),
  getPostApiV1ImpactAggregateMockHandler(),
  getGetApiV1ImpactTypeMockHandler(),
  getPostApiV1ImpactTypeMockHandler(),
  getGetApiV1ImpactTypeIdMockHandler(),
  getPutApiV1ImpactTypeIdMockHandler(),
  getDeleteApiV1ImpactTypeIdMockHandler(),
  getPostApiV1MonthlyAggregationMockHandler(),
  getDeleteApiV1MonthlyAggregationMockHandler(),
  getGetApiV1MonthlyAggregationLatestMonthAggClassificationTimePeriodMockHandler(),
  getPostApiV1MonthlyAggregationHotspotsMockHandler(),
  getPostApiV1MonthlyAggregationSourceSourceIdMockHandler(),
  getPostApiV1MonthlyAggregationSegmentMockHandler(),
  getDeleteApiV1MonthlyAggregationDuplicatesMockHandler(),
  getGetApiV1MonthlyAggregationSegmentsSegmentIdMonthAggClassificationTimePeriodMockHandler(),
  getGetApiV1MonthlyAggregationFilteringTimePeriodsMockHandler(),
  getGetApiV1MonthlyAggregationMonthAggClassificationsMockHandler(),
  getGetApiV1MonthlyAggregationSpeedCategoryFiltersMockHandler(),
  getGetApiV1RegionMockHandler(),
  getGetApiV1SegmentMockHandler(),
  getPostApiV1SegmentMockHandler(),
  getGetApiV1SegmentAllSegmentsMockHandler(),
  getGetApiV1SegmentSegmentIdMockHandler(),
  getPostApiV1SegmentSpeedsMockHandler(),
  getPostApiV1SegmentSegmentIdSpeedsMockHandler(),
  getPostApiV1SegmentAddSegmentMockHandler(),
  getPostApiV1SegmentSegmentIdEntitiesReplaceMockHandler(),
  getPostApiV1SegmentSegmentIdEntitiesAddMockHandler(),
  getDeleteApiV1SegmentSegmentIdEntitiesDeleteMockHandler(),
  getPutApiV1SegmentUpdateSegmentSegmentIdMockHandler(),
  getDeleteApiV1SegmentDeleteSegmentSegmentIdMockHandler(),
  getPostApiV1SpeedComplianceGetReportDataMockHandler(),
  getPostApiV1SpeedFromImpactImpactImpactIdMockHandler(),
  getPostApiV1SpeedFromImpactSegmentSegmentIdMockHandler(),
  getGetRouteSpeedsMockHandler(),
  getPostApiV1SpeedManagementGetMonthlyHistoricalSpeedsMockHandler(),
  getPostApiV1SpeedManagementGetDailyHistoricalSpeedsMockHandler(),
  getPostApiV1SpeedOverDistanceGetReportDataMockHandler(),
  getPostApiV1SpeedOverTimeGetReportDataMockHandler(),
  getPostApiV1SpeedVariabilityGetReportDataMockHandler(),
  getPostApiV1SpeedViolationsGetReportDataMockHandler(),
  getPostApiV1ViolationsAndExtremeViolationsGetReportDataMockHandler()
]
