/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Atspm Configuration Api
 * Atspm Device and Location Configuration
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetLocationTypeCountParams,
  GetLocationTypeFromKeyParams,
  GetLocationTypeLocationsCountFromKeyParams,
  GetLocationTypeLocationsFromKeyParams,
  GetLocationTypeParams,
  Location,
  LocationType,
  PatchLocationTypeFromKeyParams,
  PostLocationTypeParams,
  PutLocationTypeFromKeyParams
} from '../config-api.schemas';

import { configRequest } from '../../../lib/axios';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Utah.Udot.Atspm.Data.Models.Location navigation property action
 */
export const getLocationTypeLocationsFromKey = (
    key: number,
    params?: GetLocationTypeLocationsFromKeyParams,
 signal?: AbortSignal
) => {


      return configRequest<Location[]>(
      {url: `/LocationType/${key}/locations`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetLocationTypeLocationsFromKeyQueryKey = (key: number,
    params?: GetLocationTypeLocationsFromKeyParams,) => {
    return [
    `/LocationType/${key}/locations`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationTypeLocationsFromKeyQueryOptions = <TData = Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>, TError = void>(key: number,
    params?: GetLocationTypeLocationsFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationTypeLocationsFromKeyQueryKey(key,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>> = ({ signal }) => getLocationTypeLocationsFromKey(key,params, signal);





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationTypeLocationsFromKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>>
export type GetLocationTypeLocationsFromKeyQueryError = void


export function useGetLocationTypeLocationsFromKey<TData = Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>, TError = void>(
 key: number,
    params: undefined |  GetLocationTypeLocationsFromKeyParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>,
          TError,
          Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTypeLocationsFromKey<TData = Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>, TError = void>(
 key: number,
    params?: GetLocationTypeLocationsFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>,
          TError,
          Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTypeLocationsFromKey<TData = Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>, TError = void>(
 key: number,
    params?: GetLocationTypeLocationsFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Utah.Udot.Atspm.Data.Models.Location navigation property action
 */

export function useGetLocationTypeLocationsFromKey<TData = Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>, TError = void>(
 key: number,
    params?: GetLocationTypeLocationsFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeLocationsFromKey>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationTypeLocationsFromKeyQueryOptions(key,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Utah.Udot.Atspm.Data.Models.Location navigation property action
 */
export const getLocationTypeLocationsCountFromKey = (
    key: number,
    params?: GetLocationTypeLocationsCountFromKeyParams,
 signal?: AbortSignal
) => {


      return configRequest<Location[]>(
      {url: `/LocationType/${key}/locations/$count`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetLocationTypeLocationsCountFromKeyQueryKey = (key: number,
    params?: GetLocationTypeLocationsCountFromKeyParams,) => {
    return [
    `/LocationType/${key}/locations/$count`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationTypeLocationsCountFromKeyQueryOptions = <TData = Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>, TError = void>(key: number,
    params?: GetLocationTypeLocationsCountFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationTypeLocationsCountFromKeyQueryKey(key,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>> = ({ signal }) => getLocationTypeLocationsCountFromKey(key,params, signal);





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationTypeLocationsCountFromKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>>
export type GetLocationTypeLocationsCountFromKeyQueryError = void


export function useGetLocationTypeLocationsCountFromKey<TData = Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>, TError = void>(
 key: number,
    params: undefined |  GetLocationTypeLocationsCountFromKeyParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>,
          TError,
          Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTypeLocationsCountFromKey<TData = Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>, TError = void>(
 key: number,
    params?: GetLocationTypeLocationsCountFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>,
          TError,
          Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTypeLocationsCountFromKey<TData = Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>, TError = void>(
 key: number,
    params?: GetLocationTypeLocationsCountFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Utah.Udot.Atspm.Data.Models.Location navigation property action
 */

export function useGetLocationTypeLocationsCountFromKey<TData = Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>, TError = void>(
 key: number,
    params?: GetLocationTypeLocationsCountFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeLocationsCountFromKey>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationTypeLocationsCountFromKeyQueryOptions(key,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getLocationType = (
    params?: GetLocationTypeParams,
 signal?: AbortSignal
) => {


      return configRequest<LocationType[]>(
      {url: `/LocationType`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetLocationTypeQueryKey = (params?: GetLocationTypeParams,) => {
    return [
    `/LocationType`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationTypeQueryOptions = <TData = Awaited<ReturnType<typeof getLocationType>>, TError = void>(params?: GetLocationTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationType>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationTypeQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationType>>> = ({ signal }) => getLocationType(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationType>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationTypeQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationType>>>
export type GetLocationTypeQueryError = void


export function useGetLocationType<TData = Awaited<ReturnType<typeof getLocationType>>, TError = void>(
 params: undefined |  GetLocationTypeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationType>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationType>>,
          TError,
          Awaited<ReturnType<typeof getLocationType>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationType<TData = Awaited<ReturnType<typeof getLocationType>>, TError = void>(
 params?: GetLocationTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationType>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationType>>,
          TError,
          Awaited<ReturnType<typeof getLocationType>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationType<TData = Awaited<ReturnType<typeof getLocationType>>, TError = void>(
 params?: GetLocationTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationType>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLocationType<TData = Awaited<ReturnType<typeof getLocationType>>, TError = void>(
 params?: GetLocationTypeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationType>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationTypeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postLocationType = (
    locationType?: LocationType,
    params?: PostLocationTypeParams,
 signal?: AbortSignal
) => {


      return configRequest<void>(
      {url: `/LocationType`, method: 'POST',
      headers: {'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true', },
      data: locationType,
        params, signal
    },
      );
    }




export const getPostLocationTypeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLocationType>>, TError,{data?: LocationType;params?: PostLocationTypeParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postLocationType>>, TError,{data?: LocationType;params?: PostLocationTypeParams}, TContext> => {

const mutationKey = ['postLocationType'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLocationType>>, {data?: LocationType;params?: PostLocationTypeParams}> = (props) => {
          const {data,params} = props ?? {};

          return  postLocationType(data,params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLocationTypeMutationResult = NonNullable<Awaited<ReturnType<typeof postLocationType>>>
    export type PostLocationTypeMutationBody = LocationType | undefined
    export type PostLocationTypeMutationError = void

    export const usePostLocationType = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLocationType>>, TError,{data?: LocationType;params?: PostLocationTypeParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLocationType>>,
        TError,
        {data?: LocationType;params?: PostLocationTypeParams},
        TContext
      > => {
      return useMutation(getPostLocationTypeMutationOptions(options), queryClient);
    }
    export const getLocationTypeCount = (
    params?: GetLocationTypeCountParams,
 signal?: AbortSignal
) => {


      return configRequest<LocationType[]>(
      {url: `/LocationType/$count`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetLocationTypeCountQueryKey = (params?: GetLocationTypeCountParams,) => {
    return [
    `/LocationType/$count`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationTypeCountQueryOptions = <TData = Awaited<ReturnType<typeof getLocationTypeCount>>, TError = void>(params?: GetLocationTypeCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeCount>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationTypeCountQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationTypeCount>>> = ({ signal }) => getLocationTypeCount(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationTypeCountQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationTypeCount>>>
export type GetLocationTypeCountQueryError = void


export function useGetLocationTypeCount<TData = Awaited<ReturnType<typeof getLocationTypeCount>>, TError = void>(
 params: undefined |  GetLocationTypeCountParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTypeCount>>,
          TError,
          Awaited<ReturnType<typeof getLocationTypeCount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTypeCount<TData = Awaited<ReturnType<typeof getLocationTypeCount>>, TError = void>(
 params?: GetLocationTypeCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTypeCount>>,
          TError,
          Awaited<ReturnType<typeof getLocationTypeCount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTypeCount<TData = Awaited<ReturnType<typeof getLocationTypeCount>>, TError = void>(
 params?: GetLocationTypeCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeCount>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLocationTypeCount<TData = Awaited<ReturnType<typeof getLocationTypeCount>>, TError = void>(
 params?: GetLocationTypeCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeCount>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationTypeCountQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getLocationTypeFromKey = (
    key: number,
    params?: GetLocationTypeFromKeyParams,
 signal?: AbortSignal
) => {


      return configRequest<LocationType>(
      {url: `/LocationType/${key}`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetLocationTypeFromKeyQueryKey = (key: number,
    params?: GetLocationTypeFromKeyParams,) => {
    return [
    `/LocationType/${key}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLocationTypeFromKeyQueryOptions = <TData = Awaited<ReturnType<typeof getLocationTypeFromKey>>, TError = void>(key: number,
    params?: GetLocationTypeFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeFromKey>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationTypeFromKeyQueryKey(key,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocationTypeFromKey>>> = ({ signal }) => getLocationTypeFromKey(key,params, signal);





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeFromKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationTypeFromKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getLocationTypeFromKey>>>
export type GetLocationTypeFromKeyQueryError = void


export function useGetLocationTypeFromKey<TData = Awaited<ReturnType<typeof getLocationTypeFromKey>>, TError = void>(
 key: number,
    params: undefined |  GetLocationTypeFromKeyParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeFromKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTypeFromKey>>,
          TError,
          Awaited<ReturnType<typeof getLocationTypeFromKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTypeFromKey<TData = Awaited<ReturnType<typeof getLocationTypeFromKey>>, TError = void>(
 key: number,
    params?: GetLocationTypeFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeFromKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocationTypeFromKey>>,
          TError,
          Awaited<ReturnType<typeof getLocationTypeFromKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocationTypeFromKey<TData = Awaited<ReturnType<typeof getLocationTypeFromKey>>, TError = void>(
 key: number,
    params?: GetLocationTypeFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeFromKey>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLocationTypeFromKey<TData = Awaited<ReturnType<typeof getLocationTypeFromKey>>, TError = void>(
 key: number,
    params?: GetLocationTypeFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocationTypeFromKey>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationTypeFromKeyQueryOptions(key,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const putLocationTypeFromKey = (
    key: number,
    locationType?: LocationType,
    params?: PutLocationTypeFromKeyParams,
 signal?: AbortSignal
) => {


      return configRequest<void>(
      {url: `/LocationType/${key}`, method: 'PUT',
      headers: {'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true', },
      data: locationType,
        params, signal
    },
      );
    }




export const getPutLocationTypeFromKeyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putLocationTypeFromKey>>, TError,{key: number;data?: LocationType;params?: PutLocationTypeFromKeyParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putLocationTypeFromKey>>, TError,{key: number;data?: LocationType;params?: PutLocationTypeFromKeyParams}, TContext> => {

const mutationKey = ['putLocationTypeFromKey'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putLocationTypeFromKey>>, {key: number;data?: LocationType;params?: PutLocationTypeFromKeyParams}> = (props) => {
          const {key,data,params} = props ?? {};

          return  putLocationTypeFromKey(key,data,params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutLocationTypeFromKeyMutationResult = NonNullable<Awaited<ReturnType<typeof putLocationTypeFromKey>>>
    export type PutLocationTypeFromKeyMutationBody = LocationType | undefined
    export type PutLocationTypeFromKeyMutationError = void

    export const usePutLocationTypeFromKey = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putLocationTypeFromKey>>, TError,{key: number;data?: LocationType;params?: PutLocationTypeFromKeyParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putLocationTypeFromKey>>,
        TError,
        {key: number;data?: LocationType;params?: PutLocationTypeFromKeyParams},
        TContext
      > => {
      return useMutation(getPutLocationTypeFromKeyMutationOptions(options), queryClient);
    }
    export const patchLocationTypeFromKey = (
    key: number,
    locationType?: LocationType,
    params?: PatchLocationTypeFromKeyParams,
 signal?: AbortSignal
) => {


      return configRequest<void>(
      {url: `/LocationType/${key}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true', },
      data: locationType,
        params, signal
    },
      );
    }




export const getPatchLocationTypeFromKeyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchLocationTypeFromKey>>, TError,{key: number;data?: LocationType;params?: PatchLocationTypeFromKeyParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchLocationTypeFromKey>>, TError,{key: number;data?: LocationType;params?: PatchLocationTypeFromKeyParams}, TContext> => {

const mutationKey = ['patchLocationTypeFromKey'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchLocationTypeFromKey>>, {key: number;data?: LocationType;params?: PatchLocationTypeFromKeyParams}> = (props) => {
          const {key,data,params} = props ?? {};

          return  patchLocationTypeFromKey(key,data,params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchLocationTypeFromKeyMutationResult = NonNullable<Awaited<ReturnType<typeof patchLocationTypeFromKey>>>
    export type PatchLocationTypeFromKeyMutationBody = LocationType | undefined
    export type PatchLocationTypeFromKeyMutationError = void

    export const usePatchLocationTypeFromKey = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchLocationTypeFromKey>>, TError,{key: number;data?: LocationType;params?: PatchLocationTypeFromKeyParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchLocationTypeFromKey>>,
        TError,
        {key: number;data?: LocationType;params?: PatchLocationTypeFromKeyParams},
        TContext
      > => {
      return useMutation(getPatchLocationTypeFromKeyMutationOptions(options), queryClient);
    }
    export const deleteLocationTypeFromKey = (
    key: number,
 signal?: AbortSignal
) => {


      return configRequest<void>(
      {url: `/LocationType/${key}`, method: 'DELETE', signal
    },
      );
    }




export const getDeleteLocationTypeFromKeyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLocationTypeFromKey>>, TError,{key: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteLocationTypeFromKey>>, TError,{key: number}, TContext> => {

const mutationKey = ['deleteLocationTypeFromKey'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLocationTypeFromKey>>, {key: number}> = (props) => {
          const {key} = props ?? {};

          return  deleteLocationTypeFromKey(key,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteLocationTypeFromKeyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteLocationTypeFromKey>>>

    export type DeleteLocationTypeFromKeyMutationError = void

    export const useDeleteLocationTypeFromKey = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLocationTypeFromKey>>, TError,{key: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteLocationTypeFromKey>>,
        TError,
        {key: number},
        TContext
      > => {
      return useMutation(getDeleteLocationTypeFromKeyMutationOptions(options), queryClient);
    }
