/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ATSPM Report Api
 * ATSPM Reporting with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GapDurationOptions,
  GapDurationResult,
  ProblemDetails
} from '../report-api.schemas';

import { reportsRequest } from '../../../lib/axios';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Get example data for testing
 */
export const getLeftTurnGapDurationTestData = (

 signal?: AbortSignal
) => {


      return reportsRequest<GapDurationResult>(
      {url: `/api/v1/LeftTurnGapDuration/test`, method: 'GET', signal
    },
      );
    }




export const getGetLeftTurnGapDurationTestDataQueryKey = () => {
    return [
    `/api/v1/LeftTurnGapDuration/test`
    ] as const;
    }


export const getGetLeftTurnGapDurationTestDataQueryOptions = <TData = Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLeftTurnGapDurationTestDataQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>> = ({ signal }) => getLeftTurnGapDurationTestData(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLeftTurnGapDurationTestDataQueryResult = NonNullable<Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>>
export type GetLeftTurnGapDurationTestDataQueryError = ProblemDetails


export function useGetLeftTurnGapDurationTestData<TData = Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>,
          TError,
          Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLeftTurnGapDurationTestData<TData = Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>,
          TError,
          Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLeftTurnGapDurationTestData<TData = Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get example data for testing
 */

export function useGetLeftTurnGapDurationTestData<TData = Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLeftTurnGapDurationTestDataQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Get report data
 */
export const getLeftTurnGapDurationReportData = (
    gapDurationOptions?: GapDurationOptions,
 signal?: AbortSignal
) => {


      return reportsRequest<GapDurationResult>(
      {url: `/api/v1/LeftTurnGapDuration/getReportData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gapDurationOptions, signal
    },
      );
    }




export const getGetLeftTurnGapDurationReportDataMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationReportData>>, TError,{data?: GapDurationOptions}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationReportData>>, TError,{data?: GapDurationOptions}, TContext> => {

const mutationKey = ['getLeftTurnGapDurationReportData'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getLeftTurnGapDurationReportData>>, {data?: GapDurationOptions}> = (props) => {
          const {data} = props ?? {};

          return  getLeftTurnGapDurationReportData(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetLeftTurnGapDurationReportDataMutationResult = NonNullable<Awaited<ReturnType<typeof getLeftTurnGapDurationReportData>>>
    export type GetLeftTurnGapDurationReportDataMutationBody = GapDurationOptions | undefined
    export type GetLeftTurnGapDurationReportDataMutationError = ProblemDetails

    /**
 * @summary Get report data
 */
export const useGetLeftTurnGapDurationReportData = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationReportData>>, TError,{data?: GapDurationOptions}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getLeftTurnGapDurationReportData>>,
        TError,
        {data?: GapDurationOptions},
        TContext
      > => {
      return useMutation(getGetLeftTurnGapDurationReportDataMutationOptions(options), queryClient);
    }
