/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Atspm Configuration Api
 * Atspm Device and Location Configuration
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Location,
  Region
} from '../config-api.schemas';

import {
  getGetRegionCountResponseMock,
  getGetRegionFromKeyResponseMock,
  getGetRegionLocationsCountFromKeyResponseMock,
  getGetRegionLocationsFromKeyResponseMock,
  getGetRegionResponseMock
} from './region.faker';

export { getGetRegionLocationsFromKeyResponseMock, getGetRegionLocationsCountFromKeyResponseMock, getGetRegionResponseMock, getGetRegionCountResponseMock, getGetRegionFromKeyResponseMock } from './region.faker';


export const getGetRegionLocationsFromKeyMockHandler = (overrideResponse?: Location[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Location[]> | Location[]), options?: RequestHandlerOptions) => {
  return http.get('*/Region/:key/locations', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetRegionLocationsFromKeyResponseMock(),
      { status: 200, headers: { 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true' }
      })
  }, options)
}

export const getGetRegionLocationsCountFromKeyMockHandler = (overrideResponse?: Location[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Location[]> | Location[]), options?: RequestHandlerOptions) => {
  return http.get('*/Region/:key/locations/$count', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetRegionLocationsCountFromKeyResponseMock(),
      { status: 200, headers: { 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true' }
      })
  }, options)
}

export const getGetRegionMockHandler = (overrideResponse?: Region[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Region[]> | Region[]), options?: RequestHandlerOptions) => {
  return http.get('*/Region', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetRegionResponseMock(),
      { status: 200, headers: { 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true' }
      })
  }, options)
}

export const getPostRegionMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/Region', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 201
      })
  }, options)
}

export const getGetRegionCountMockHandler = (overrideResponse?: Region[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Region[]> | Region[]), options?: RequestHandlerOptions) => {
  return http.get('*/Region/$count', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetRegionCountResponseMock(),
      { status: 200, headers: { 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true' }
      })
  }, options)
}

export const getGetRegionFromKeyMockHandler = (overrideResponse?: Region | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Region> | Region), options?: RequestHandlerOptions) => {
  return http.get('*/Region/:key', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetRegionFromKeyResponseMock(),
      { status: 200, headers: { 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true' }
      })
  }, options)
}

export const getPutRegionFromKeyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/Region/:key', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getPatchRegionFromKeyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.patch('*/Region/:key', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getDeleteRegionFromKeyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/Region/:key', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}
export const getRegionMock = () => [
  getGetRegionLocationsFromKeyMockHandler(),
  getGetRegionLocationsCountFromKeyMockHandler(),
  getGetRegionMockHandler(),
  getPostRegionMockHandler(),
  getGetRegionCountMockHandler(),
  getGetRegionFromKeyMockHandler(),
  getPutRegionFromKeyMockHandler(),
  getPatchRegionFromKeyMockHandler(),
  getDeleteRegionFromKeyMockHandler()
]
