/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Atspm Configuration Api
 * Atspm Device and Location Configuration
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  MeasureOption
} from '../config-api.schemas';

import {
  getGetMeasureOptionCountResponseMock,
  getGetMeasureOptionFromKeyResponseMock,
  getGetMeasureOptionResponseMock
} from './measure-option.faker';

export { getGetMeasureOptionResponseMock, getGetMeasureOptionCountResponseMock, getGetMeasureOptionFromKeyResponseMock } from './measure-option.faker';


export const getGetMeasureOptionMockHandler = (overrideResponse?: MeasureOption[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MeasureOption[]> | MeasureOption[]), options?: RequestHandlerOptions) => {
  return http.get('*/MeasureOption', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMeasureOptionResponseMock(),
      { status: 200, headers: { 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true' }
      })
  }, options)
}

export const getPostMeasureOptionMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/MeasureOption', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 201
      })
  }, options)
}

export const getGetMeasureOptionCountMockHandler = (overrideResponse?: MeasureOption[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MeasureOption[]> | MeasureOption[]), options?: RequestHandlerOptions) => {
  return http.get('*/MeasureOption/$count', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMeasureOptionCountResponseMock(),
      { status: 200, headers: { 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true' }
      })
  }, options)
}

export const getGetMeasureOptionFromKeyMockHandler = (overrideResponse?: MeasureOption | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MeasureOption> | MeasureOption), options?: RequestHandlerOptions) => {
  return http.get('*/MeasureOption/:key', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMeasureOptionFromKeyResponseMock(),
      { status: 200, headers: { 'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true' }
      })
  }, options)
}

export const getPutMeasureOptionFromKeyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/MeasureOption/:key', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getPatchMeasureOptionFromKeyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.patch('*/MeasureOption/:key', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getDeleteMeasureOptionFromKeyMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/MeasureOption/:key', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}
export const getMeasureOptionMock = () => [
  getGetMeasureOptionMockHandler(),
  getPostMeasureOptionMockHandler(),
  getGetMeasureOptionCountMockHandler(),
  getGetMeasureOptionFromKeyMockHandler(),
  getPutMeasureOptionFromKeyMockHandler(),
  getPatchMeasureOptionFromKeyMockHandler(),
  getDeleteMeasureOptionFromKeyMockHandler()
]
