/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Atspm Configuration Api
 * Atspm Device and Location Configuration
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetMeasureOptionCountParams,
  GetMeasureOptionFromKeyParams,
  GetMeasureOptionParams,
  MeasureOption,
  PatchMeasureOptionFromKeyParams,
  PostMeasureOptionParams,
  PutMeasureOptionFromKeyParams
} from '../config-api.schemas';

import { configRequest } from '../../../lib/axios';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getMeasureOption = (
    params?: GetMeasureOptionParams,
 signal?: AbortSignal
) => {


      return configRequest<MeasureOption[]>(
      {url: `/MeasureOption`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetMeasureOptionQueryKey = (params?: GetMeasureOptionParams,) => {
    return [
    `/MeasureOption`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetMeasureOptionQueryOptions = <TData = Awaited<ReturnType<typeof getMeasureOption>>, TError = void>(params?: GetMeasureOptionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOption>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeasureOptionQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeasureOption>>> = ({ signal }) => getMeasureOption(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeasureOption>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeasureOptionQueryResult = NonNullable<Awaited<ReturnType<typeof getMeasureOption>>>
export type GetMeasureOptionQueryError = void


export function useGetMeasureOption<TData = Awaited<ReturnType<typeof getMeasureOption>>, TError = void>(
 params: undefined |  GetMeasureOptionParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOption>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeasureOption>>,
          TError,
          Awaited<ReturnType<typeof getMeasureOption>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeasureOption<TData = Awaited<ReturnType<typeof getMeasureOption>>, TError = void>(
 params?: GetMeasureOptionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOption>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeasureOption>>,
          TError,
          Awaited<ReturnType<typeof getMeasureOption>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeasureOption<TData = Awaited<ReturnType<typeof getMeasureOption>>, TError = void>(
 params?: GetMeasureOptionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOption>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMeasureOption<TData = Awaited<ReturnType<typeof getMeasureOption>>, TError = void>(
 params?: GetMeasureOptionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOption>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeasureOptionQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postMeasureOption = (
    measureOption?: MeasureOption,
    params?: PostMeasureOptionParams,
 signal?: AbortSignal
) => {


      return configRequest<void>(
      {url: `/MeasureOption`, method: 'POST',
      headers: {'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true', },
      data: measureOption,
        params, signal
    },
      );
    }




export const getPostMeasureOptionMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMeasureOption>>, TError,{data?: MeasureOption;params?: PostMeasureOptionParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postMeasureOption>>, TError,{data?: MeasureOption;params?: PostMeasureOptionParams}, TContext> => {

const mutationKey = ['postMeasureOption'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postMeasureOption>>, {data?: MeasureOption;params?: PostMeasureOptionParams}> = (props) => {
          const {data,params} = props ?? {};

          return  postMeasureOption(data,params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostMeasureOptionMutationResult = NonNullable<Awaited<ReturnType<typeof postMeasureOption>>>
    export type PostMeasureOptionMutationBody = MeasureOption | undefined
    export type PostMeasureOptionMutationError = void

    export const usePostMeasureOption = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMeasureOption>>, TError,{data?: MeasureOption;params?: PostMeasureOptionParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postMeasureOption>>,
        TError,
        {data?: MeasureOption;params?: PostMeasureOptionParams},
        TContext
      > => {
      return useMutation(getPostMeasureOptionMutationOptions(options), queryClient);
    }
    export const getMeasureOptionCount = (
    params?: GetMeasureOptionCountParams,
 signal?: AbortSignal
) => {


      return configRequest<MeasureOption[]>(
      {url: `/MeasureOption/$count`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetMeasureOptionCountQueryKey = (params?: GetMeasureOptionCountParams,) => {
    return [
    `/MeasureOption/$count`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetMeasureOptionCountQueryOptions = <TData = Awaited<ReturnType<typeof getMeasureOptionCount>>, TError = void>(params?: GetMeasureOptionCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOptionCount>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeasureOptionCountQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeasureOptionCount>>> = ({ signal }) => getMeasureOptionCount(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeasureOptionCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeasureOptionCountQueryResult = NonNullable<Awaited<ReturnType<typeof getMeasureOptionCount>>>
export type GetMeasureOptionCountQueryError = void


export function useGetMeasureOptionCount<TData = Awaited<ReturnType<typeof getMeasureOptionCount>>, TError = void>(
 params: undefined |  GetMeasureOptionCountParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOptionCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeasureOptionCount>>,
          TError,
          Awaited<ReturnType<typeof getMeasureOptionCount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeasureOptionCount<TData = Awaited<ReturnType<typeof getMeasureOptionCount>>, TError = void>(
 params?: GetMeasureOptionCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOptionCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeasureOptionCount>>,
          TError,
          Awaited<ReturnType<typeof getMeasureOptionCount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeasureOptionCount<TData = Awaited<ReturnType<typeof getMeasureOptionCount>>, TError = void>(
 params?: GetMeasureOptionCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOptionCount>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMeasureOptionCount<TData = Awaited<ReturnType<typeof getMeasureOptionCount>>, TError = void>(
 params?: GetMeasureOptionCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOptionCount>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeasureOptionCountQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getMeasureOptionFromKey = (
    key: number,
    params?: GetMeasureOptionFromKeyParams,
 signal?: AbortSignal
) => {


      return configRequest<MeasureOption>(
      {url: `/MeasureOption/${key}`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetMeasureOptionFromKeyQueryKey = (key: number,
    params?: GetMeasureOptionFromKeyParams,) => {
    return [
    `/MeasureOption/${key}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetMeasureOptionFromKeyQueryOptions = <TData = Awaited<ReturnType<typeof getMeasureOptionFromKey>>, TError = void>(key: number,
    params?: GetMeasureOptionFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOptionFromKey>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeasureOptionFromKeyQueryKey(key,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeasureOptionFromKey>>> = ({ signal }) => getMeasureOptionFromKey(key,params, signal);





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeasureOptionFromKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeasureOptionFromKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getMeasureOptionFromKey>>>
export type GetMeasureOptionFromKeyQueryError = void


export function useGetMeasureOptionFromKey<TData = Awaited<ReturnType<typeof getMeasureOptionFromKey>>, TError = void>(
 key: number,
    params: undefined |  GetMeasureOptionFromKeyParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOptionFromKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeasureOptionFromKey>>,
          TError,
          Awaited<ReturnType<typeof getMeasureOptionFromKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeasureOptionFromKey<TData = Awaited<ReturnType<typeof getMeasureOptionFromKey>>, TError = void>(
 key: number,
    params?: GetMeasureOptionFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOptionFromKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeasureOptionFromKey>>,
          TError,
          Awaited<ReturnType<typeof getMeasureOptionFromKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeasureOptionFromKey<TData = Awaited<ReturnType<typeof getMeasureOptionFromKey>>, TError = void>(
 key: number,
    params?: GetMeasureOptionFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOptionFromKey>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMeasureOptionFromKey<TData = Awaited<ReturnType<typeof getMeasureOptionFromKey>>, TError = void>(
 key: number,
    params?: GetMeasureOptionFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeasureOptionFromKey>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeasureOptionFromKeyQueryOptions(key,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const putMeasureOptionFromKey = (
    key: number,
    measureOption?: MeasureOption,
    params?: PutMeasureOptionFromKeyParams,
 signal?: AbortSignal
) => {


      return configRequest<void>(
      {url: `/MeasureOption/${key}`, method: 'PUT',
      headers: {'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true', },
      data: measureOption,
        params, signal
    },
      );
    }




export const getPutMeasureOptionFromKeyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putMeasureOptionFromKey>>, TError,{key: number;data?: MeasureOption;params?: PutMeasureOptionFromKeyParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putMeasureOptionFromKey>>, TError,{key: number;data?: MeasureOption;params?: PutMeasureOptionFromKeyParams}, TContext> => {

const mutationKey = ['putMeasureOptionFromKey'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putMeasureOptionFromKey>>, {key: number;data?: MeasureOption;params?: PutMeasureOptionFromKeyParams}> = (props) => {
          const {key,data,params} = props ?? {};

          return  putMeasureOptionFromKey(key,data,params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutMeasureOptionFromKeyMutationResult = NonNullable<Awaited<ReturnType<typeof putMeasureOptionFromKey>>>
    export type PutMeasureOptionFromKeyMutationBody = MeasureOption | undefined
    export type PutMeasureOptionFromKeyMutationError = void

    export const usePutMeasureOptionFromKey = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putMeasureOptionFromKey>>, TError,{key: number;data?: MeasureOption;params?: PutMeasureOptionFromKeyParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putMeasureOptionFromKey>>,
        TError,
        {key: number;data?: MeasureOption;params?: PutMeasureOptionFromKeyParams},
        TContext
      > => {
      return useMutation(getPutMeasureOptionFromKeyMutationOptions(options), queryClient);
    }
    export const patchMeasureOptionFromKey = (
    key: number,
    measureOption?: MeasureOption,
    params?: PatchMeasureOptionFromKeyParams,
 signal?: AbortSignal
) => {


      return configRequest<void>(
      {url: `/MeasureOption/${key}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true', },
      data: measureOption,
        params, signal
    },
      );
    }




export const getPatchMeasureOptionFromKeyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchMeasureOptionFromKey>>, TError,{key: number;data?: MeasureOption;params?: PatchMeasureOptionFromKeyParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchMeasureOptionFromKey>>, TError,{key: number;data?: MeasureOption;params?: PatchMeasureOptionFromKeyParams}, TContext> => {

const mutationKey = ['patchMeasureOptionFromKey'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchMeasureOptionFromKey>>, {key: number;data?: MeasureOption;params?: PatchMeasureOptionFromKeyParams}> = (props) => {
          const {key,data,params} = props ?? {};

          return  patchMeasureOptionFromKey(key,data,params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchMeasureOptionFromKeyMutationResult = NonNullable<Awaited<ReturnType<typeof patchMeasureOptionFromKey>>>
    export type PatchMeasureOptionFromKeyMutationBody = MeasureOption | undefined
    export type PatchMeasureOptionFromKeyMutationError = void

    export const usePatchMeasureOptionFromKey = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchMeasureOptionFromKey>>, TError,{key: number;data?: MeasureOption;params?: PatchMeasureOptionFromKeyParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchMeasureOptionFromKey>>,
        TError,
        {key: number;data?: MeasureOption;params?: PatchMeasureOptionFromKeyParams},
        TContext
      > => {
      return useMutation(getPatchMeasureOptionFromKeyMutationOptions(options), queryClient);
    }
    export const deleteMeasureOptionFromKey = (
    key: number,
 signal?: AbortSignal
) => {


      return configRequest<void>(
      {url: `/MeasureOption/${key}`, method: 'DELETE', signal
    },
      );
    }




export const getDeleteMeasureOptionFromKeyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMeasureOptionFromKey>>, TError,{key: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteMeasureOptionFromKey>>, TError,{key: number}, TContext> => {

const mutationKey = ['deleteMeasureOptionFromKey'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMeasureOptionFromKey>>, {key: number}> = (props) => {
          const {key} = props ?? {};

          return  deleteMeasureOptionFromKey(key,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteMeasureOptionFromKeyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMeasureOptionFromKey>>>

    export type DeleteMeasureOptionFromKeyMutationError = void

    export const useDeleteMeasureOptionFromKey = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMeasureOptionFromKey>>, TError,{key: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMeasureOptionFromKey>>,
        TError,
        {key: number},
        TContext
      > => {
      return useMutation(getDeleteMeasureOptionFromKeyMutationOptions(options), queryClient);
    }
