/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Atspm Configuration Api
 * Atspm Device and Location Configuration
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetWatchDogIgnoreEventCountParams,
  GetWatchDogIgnoreEventFromKeyParams,
  GetWatchDogIgnoreEventParams,
  PatchWatchDogIgnoreEventFromKeyParams,
  PostWatchDogIgnoreEventParams,
  PutWatchDogIgnoreEventFromKeyParams,
  WatchDogIgnoreEvent
} from '../config-api.schemas';

import { configRequest } from '../../../lib/axios';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getWatchDogIgnoreEvent = (
    params?: GetWatchDogIgnoreEventParams,
 signal?: AbortSignal
) => {


      return configRequest<WatchDogIgnoreEvent[]>(
      {url: `/WatchDogIgnoreEvent`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetWatchDogIgnoreEventQueryKey = (params?: GetWatchDogIgnoreEventParams,) => {
    return [
    `/WatchDogIgnoreEvent`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetWatchDogIgnoreEventQueryOptions = <TData = Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>, TError = void>(params?: GetWatchDogIgnoreEventParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWatchDogIgnoreEventQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>> = ({ signal }) => getWatchDogIgnoreEvent(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWatchDogIgnoreEventQueryResult = NonNullable<Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>>
export type GetWatchDogIgnoreEventQueryError = void


export function useGetWatchDogIgnoreEvent<TData = Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>, TError = void>(
 params: undefined |  GetWatchDogIgnoreEventParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>,
          TError,
          Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWatchDogIgnoreEvent<TData = Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>, TError = void>(
 params?: GetWatchDogIgnoreEventParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>,
          TError,
          Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWatchDogIgnoreEvent<TData = Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>, TError = void>(
 params?: GetWatchDogIgnoreEventParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetWatchDogIgnoreEvent<TData = Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>, TError = void>(
 params?: GetWatchDogIgnoreEventParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEvent>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWatchDogIgnoreEventQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postWatchDogIgnoreEvent = (
    watchDogIgnoreEvent?: WatchDogIgnoreEvent,
    params?: PostWatchDogIgnoreEventParams,
 signal?: AbortSignal
) => {


      return configRequest<void>(
      {url: `/WatchDogIgnoreEvent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: watchDogIgnoreEvent,
        params, signal
    },
      );
    }




export const getPostWatchDogIgnoreEventMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWatchDogIgnoreEvent>>, TError,{data?: WatchDogIgnoreEvent;params?: PostWatchDogIgnoreEventParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postWatchDogIgnoreEvent>>, TError,{data?: WatchDogIgnoreEvent;params?: PostWatchDogIgnoreEventParams}, TContext> => {

const mutationKey = ['postWatchDogIgnoreEvent'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWatchDogIgnoreEvent>>, {data?: WatchDogIgnoreEvent;params?: PostWatchDogIgnoreEventParams}> = (props) => {
          const {data,params} = props ?? {};

          return  postWatchDogIgnoreEvent(data,params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostWatchDogIgnoreEventMutationResult = NonNullable<Awaited<ReturnType<typeof postWatchDogIgnoreEvent>>>
    export type PostWatchDogIgnoreEventMutationBody = WatchDogIgnoreEvent | undefined
    export type PostWatchDogIgnoreEventMutationError = void

    export const usePostWatchDogIgnoreEvent = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWatchDogIgnoreEvent>>, TError,{data?: WatchDogIgnoreEvent;params?: PostWatchDogIgnoreEventParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWatchDogIgnoreEvent>>,
        TError,
        {data?: WatchDogIgnoreEvent;params?: PostWatchDogIgnoreEventParams},
        TContext
      > => {
      return useMutation(getPostWatchDogIgnoreEventMutationOptions(options), queryClient);
    }
    export const getWatchDogIgnoreEventCount = (
    params?: GetWatchDogIgnoreEventCountParams,
 signal?: AbortSignal
) => {


      return configRequest<WatchDogIgnoreEvent[]>(
      {url: `/WatchDogIgnoreEvent/$count`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetWatchDogIgnoreEventCountQueryKey = (params?: GetWatchDogIgnoreEventCountParams,) => {
    return [
    `/WatchDogIgnoreEvent/$count`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetWatchDogIgnoreEventCountQueryOptions = <TData = Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>, TError = void>(params?: GetWatchDogIgnoreEventCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWatchDogIgnoreEventCountQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>> = ({ signal }) => getWatchDogIgnoreEventCount(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWatchDogIgnoreEventCountQueryResult = NonNullable<Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>>
export type GetWatchDogIgnoreEventCountQueryError = void


export function useGetWatchDogIgnoreEventCount<TData = Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>, TError = void>(
 params: undefined |  GetWatchDogIgnoreEventCountParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>,
          TError,
          Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWatchDogIgnoreEventCount<TData = Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>, TError = void>(
 params?: GetWatchDogIgnoreEventCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>,
          TError,
          Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWatchDogIgnoreEventCount<TData = Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>, TError = void>(
 params?: GetWatchDogIgnoreEventCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetWatchDogIgnoreEventCount<TData = Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>, TError = void>(
 params?: GetWatchDogIgnoreEventCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEventCount>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWatchDogIgnoreEventCountQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getWatchDogIgnoreEventFromKey = (
    key: number,
    params?: GetWatchDogIgnoreEventFromKeyParams,
 signal?: AbortSignal
) => {


      return configRequest<WatchDogIgnoreEvent>(
      {url: `/WatchDogIgnoreEvent/${key}`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetWatchDogIgnoreEventFromKeyQueryKey = (key: number,
    params?: GetWatchDogIgnoreEventFromKeyParams,) => {
    return [
    `/WatchDogIgnoreEvent/${key}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetWatchDogIgnoreEventFromKeyQueryOptions = <TData = Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>, TError = void>(key: number,
    params?: GetWatchDogIgnoreEventFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWatchDogIgnoreEventFromKeyQueryKey(key,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>> = ({ signal }) => getWatchDogIgnoreEventFromKey(key,params, signal);





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWatchDogIgnoreEventFromKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>>
export type GetWatchDogIgnoreEventFromKeyQueryError = void


export function useGetWatchDogIgnoreEventFromKey<TData = Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>, TError = void>(
 key: number,
    params: undefined |  GetWatchDogIgnoreEventFromKeyParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>,
          TError,
          Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWatchDogIgnoreEventFromKey<TData = Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>, TError = void>(
 key: number,
    params?: GetWatchDogIgnoreEventFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>,
          TError,
          Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWatchDogIgnoreEventFromKey<TData = Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>, TError = void>(
 key: number,
    params?: GetWatchDogIgnoreEventFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetWatchDogIgnoreEventFromKey<TData = Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>, TError = void>(
 key: number,
    params?: GetWatchDogIgnoreEventFromKeyParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWatchDogIgnoreEventFromKey>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWatchDogIgnoreEventFromKeyQueryOptions(key,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const putWatchDogIgnoreEventFromKey = (
    key: number,
    watchDogIgnoreEvent?: WatchDogIgnoreEvent,
    params?: PutWatchDogIgnoreEventFromKeyParams,
 signal?: AbortSignal
) => {


      return configRequest<void>(
      {url: `/WatchDogIgnoreEvent/${key}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: watchDogIgnoreEvent,
        params, signal
    },
      );
    }




export const getPutWatchDogIgnoreEventFromKeyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putWatchDogIgnoreEventFromKey>>, TError,{key: number;data?: WatchDogIgnoreEvent;params?: PutWatchDogIgnoreEventFromKeyParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putWatchDogIgnoreEventFromKey>>, TError,{key: number;data?: WatchDogIgnoreEvent;params?: PutWatchDogIgnoreEventFromKeyParams}, TContext> => {

const mutationKey = ['putWatchDogIgnoreEventFromKey'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putWatchDogIgnoreEventFromKey>>, {key: number;data?: WatchDogIgnoreEvent;params?: PutWatchDogIgnoreEventFromKeyParams}> = (props) => {
          const {key,data,params} = props ?? {};

          return  putWatchDogIgnoreEventFromKey(key,data,params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutWatchDogIgnoreEventFromKeyMutationResult = NonNullable<Awaited<ReturnType<typeof putWatchDogIgnoreEventFromKey>>>
    export type PutWatchDogIgnoreEventFromKeyMutationBody = WatchDogIgnoreEvent | undefined
    export type PutWatchDogIgnoreEventFromKeyMutationError = void

    export const usePutWatchDogIgnoreEventFromKey = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putWatchDogIgnoreEventFromKey>>, TError,{key: number;data?: WatchDogIgnoreEvent;params?: PutWatchDogIgnoreEventFromKeyParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putWatchDogIgnoreEventFromKey>>,
        TError,
        {key: number;data?: WatchDogIgnoreEvent;params?: PutWatchDogIgnoreEventFromKeyParams},
        TContext
      > => {
      return useMutation(getPutWatchDogIgnoreEventFromKeyMutationOptions(options), queryClient);
    }
    export const patchWatchDogIgnoreEventFromKey = (
    key: number,
    watchDogIgnoreEvent?: WatchDogIgnoreEvent,
    params?: PatchWatchDogIgnoreEventFromKeyParams,
 signal?: AbortSignal
) => {


      return configRequest<void>(
      {url: `/WatchDogIgnoreEvent/${key}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: watchDogIgnoreEvent,
        params, signal
    },
      );
    }




export const getPatchWatchDogIgnoreEventFromKeyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchWatchDogIgnoreEventFromKey>>, TError,{key: number;data?: WatchDogIgnoreEvent;params?: PatchWatchDogIgnoreEventFromKeyParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchWatchDogIgnoreEventFromKey>>, TError,{key: number;data?: WatchDogIgnoreEvent;params?: PatchWatchDogIgnoreEventFromKeyParams}, TContext> => {

const mutationKey = ['patchWatchDogIgnoreEventFromKey'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchWatchDogIgnoreEventFromKey>>, {key: number;data?: WatchDogIgnoreEvent;params?: PatchWatchDogIgnoreEventFromKeyParams}> = (props) => {
          const {key,data,params} = props ?? {};

          return  patchWatchDogIgnoreEventFromKey(key,data,params,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchWatchDogIgnoreEventFromKeyMutationResult = NonNullable<Awaited<ReturnType<typeof patchWatchDogIgnoreEventFromKey>>>
    export type PatchWatchDogIgnoreEventFromKeyMutationBody = WatchDogIgnoreEvent | undefined
    export type PatchWatchDogIgnoreEventFromKeyMutationError = void

    export const usePatchWatchDogIgnoreEventFromKey = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchWatchDogIgnoreEventFromKey>>, TError,{key: number;data?: WatchDogIgnoreEvent;params?: PatchWatchDogIgnoreEventFromKeyParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchWatchDogIgnoreEventFromKey>>,
        TError,
        {key: number;data?: WatchDogIgnoreEvent;params?: PatchWatchDogIgnoreEventFromKeyParams},
        TContext
      > => {
      return useMutation(getPatchWatchDogIgnoreEventFromKeyMutationOptions(options), queryClient);
    }
    export const deleteWatchDogIgnoreEventFromKey = (
    key: number,
 signal?: AbortSignal
) => {


      return configRequest<void>(
      {url: `/WatchDogIgnoreEvent/${key}`, method: 'DELETE', signal
    },
      );
    }




export const getDeleteWatchDogIgnoreEventFromKeyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWatchDogIgnoreEventFromKey>>, TError,{key: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteWatchDogIgnoreEventFromKey>>, TError,{key: number}, TContext> => {

const mutationKey = ['deleteWatchDogIgnoreEventFromKey'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWatchDogIgnoreEventFromKey>>, {key: number}> = (props) => {
          const {key} = props ?? {};

          return  deleteWatchDogIgnoreEventFromKey(key,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteWatchDogIgnoreEventFromKeyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWatchDogIgnoreEventFromKey>>>

    export type DeleteWatchDogIgnoreEventFromKeyMutationError = void

    export const useDeleteWatchDogIgnoreEventFromKey = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWatchDogIgnoreEventFromKey>>, TError,{key: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWatchDogIgnoreEventFromKey>>,
        TError,
        {key: number},
        TContext
      > => {
      return useMutation(getDeleteWatchDogIgnoreEventFromKeyMutationOptions(options), queryClient);
    }
